"""
author: Melanie Daeschinger
description: Test methods and look for improval process
"""

import numpy as np
import Preprocessing
import Loader
import os
import matplotlib.pyplot as plt
import time

# Time tracking
time_start = time.time()

# Constants
INPUT_FOLDER = os.getcwd() + '/input/sample_images/'
patients = os.listdir(INPUT_FOLDER)
patients.sort()


# Load segmented lungs generated from Watershed
segmentedlung_watershed_pat12 = Loader.load_stack('Watershed_seg12.npy')
segmentedlung_watershed_pat13 = Loader.load_stack('Watershed_seg13.npy')

# Load segmented lungs generated by "Full Preprocessing Tutorial"
segmentedlung_students_pat12 = Loader.load_stack('Students_seg12.npy')
segmentedlung_students_pat13 = Loader.load_stack('Students_seg13.npy')



# Plot the segmented lung as pointcloud
Preprocessing.print_pointcloud(segmentedlung_watershed_pat12, -1500, 700)
Preprocessing.print_pointcloud(segmentedlung_students_pat12, -1500, 700)

# Plot the segmented lung as Mesh
Preprocessing.plot_3d(segmentedlung_watershed_pat12, -500)
Preprocessing.plot_3d(segmentedlung_students_pat12, -500)

print("Segmented Pic from a middle Slice")
plt.imshow(segmentedlung_watershed_pat12[100], cmap='gray')
plt.show()
plt.imshow(segmentedlung_students_pat12[100], cmap='gray')
plt.show()

plt.hist(segmentedlung_watershed_pat12.flatten(), bins=80, color='c')
plt.xlabel("Hounsfield Unit [HU]")
plt.ylabel("Frequency")
plt.show()

plt.hist(segmentedlung_students_pat12.flatten(), bins=80, color='c')
plt.xlabel("Hounsfield Unit [HU]")
plt.ylabel("Frequency")
plt.show()
